#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedrunAppLaundry
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="laundry")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDetailPaket(DetailPaket instance);
    partial void UpdateDetailPaket(DetailPaket instance);
    partial void DeleteDetailPaket(DetailPaket instance);
    partial void InsertDetailTransaksi(DetailTransaksi instance);
    partial void UpdateDetailTransaksi(DetailTransaksi instance);
    partial void DeleteDetailTransaksi(DetailTransaksi instance);
    partial void InsertJabatan(Jabatan instance);
    partial void UpdateJabatan(Jabatan instance);
    partial void DeleteJabatan(Jabatan instance);
    partial void InsertKategori(Kategori instance);
    partial void UpdateKategori(Kategori instance);
    partial void DeleteKategori(Kategori instance);
    partial void InsertLayanan(Layanan instance);
    partial void UpdateLayanan(Layanan instance);
    partial void DeleteLayanan(Layanan instance);
    partial void InsertPaket(Paket instance);
    partial void UpdatePaket(Paket instance);
    partial void DeletePaket(Paket instance);
    partial void InsertPegawai(Pegawai instance);
    partial void UpdatePegawai(Pegawai instance);
    partial void DeletePegawai(Pegawai instance);
    partial void InsertPelanggan(Pelanggan instance);
    partial void UpdatePelanggan(Pelanggan instance);
    partial void DeletePelanggan(Pelanggan instance);
    partial void InsertTransaksi(Transaksi instance);
    partial void UpdateTransaksi(Transaksi instance);
    partial void DeleteTransaksi(Transaksi instance);
    partial void InsertUnit(Unit instance);
    partial void UpdateUnit(Unit instance);
    partial void DeleteUnit(Unit instance);
    partial void InsertVoucher(Voucher instance);
    partial void UpdateVoucher(Voucher instance);
    partial void DeleteVoucher(Voucher instance);
    partial void InsertTransaksi1(Transaksi1 instance);
    partial void UpdateTransaksi1(Transaksi1 instance);
    partial void DeleteTransaksi1(Transaksi1 instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::SpeedrunAppLaundry.Properties.Settings.Default.laundryConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DetailPaket> DetailPakets
		{
			get
			{
				return this.GetTable<DetailPaket>();
			}
		}
		
		public System.Data.Linq.Table<DetailTransaksi> DetailTransaksis
		{
			get
			{
				return this.GetTable<DetailTransaksi>();
			}
		}
		
		public System.Data.Linq.Table<Jabatan> Jabatans
		{
			get
			{
				return this.GetTable<Jabatan>();
			}
		}
		
		public System.Data.Linq.Table<Kategori> Kategoris
		{
			get
			{
				return this.GetTable<Kategori>();
			}
		}
		
		public System.Data.Linq.Table<Layanan> Layanans
		{
			get
			{
				return this.GetTable<Layanan>();
			}
		}
		
		public System.Data.Linq.Table<Paket> Pakets
		{
			get
			{
				return this.GetTable<Paket>();
			}
		}
		
		public System.Data.Linq.Table<Pegawai> Pegawais
		{
			get
			{
				return this.GetTable<Pegawai>();
			}
		}
		
		public System.Data.Linq.Table<Pelanggan> Pelanggans
		{
			get
			{
				return this.GetTable<Pelanggan>();
			}
		}
		
		public System.Data.Linq.Table<Transaksi> Transaksis
		{
			get
			{
				return this.GetTable<Transaksi>();
			}
		}
		
		public System.Data.Linq.Table<Unit> Units
		{
			get
			{
				return this.GetTable<Unit>();
			}
		}
		
		public System.Data.Linq.Table<Voucher> Vouchers
		{
			get
			{
				return this.GetTable<Voucher>();
			}
		}
		
		public System.Data.Linq.Table<Transaksi1> Transaksi1s
		{
			get
			{
				return this.GetTable<Transaksi1>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DetailPaket")]
	public partial class DetailPaket : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _idPelanggan;
		
		private int _idPaket;
		
		private int _Harga;
		
		private System.DateTime _TanggalMulai;
		
		private System.Nullable<System.DateTime> _TanggalSelesai;
		
		private EntitySet<DetailTransaksi> _DetailTransaksis;
		
		private EntityRef<Paket> _Paket;
		
		private EntityRef<Pelanggan> _Pelanggan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidPelangganChanging(int value);
    partial void OnidPelangganChanged();
    partial void OnidPaketChanging(int value);
    partial void OnidPaketChanged();
    partial void OnHargaChanging(int value);
    partial void OnHargaChanged();
    partial void OnTanggalMulaiChanging(System.DateTime value);
    partial void OnTanggalMulaiChanged();
    partial void OnTanggalSelesaiChanging(System.Nullable<System.DateTime> value);
    partial void OnTanggalSelesaiChanged();
    #endregion
		
		public DetailPaket()
		{
			this._DetailTransaksis = new EntitySet<DetailTransaksi>(new Action<DetailTransaksi>(this.attach_DetailTransaksis), new Action<DetailTransaksi>(this.detach_DetailTransaksis));
			this._Paket = default(EntityRef<Paket>);
			this._Pelanggan = default(EntityRef<Pelanggan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPelanggan", DbType="Int NOT NULL")]
		public int idPelanggan
		{
			get
			{
				return this._idPelanggan;
			}
			set
			{
				if ((this._idPelanggan != value))
				{
					if (this._Pelanggan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPelangganChanging(value);
					this.SendPropertyChanging();
					this._idPelanggan = value;
					this.SendPropertyChanged("idPelanggan");
					this.OnidPelangganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPaket", DbType="Int NOT NULL")]
		public int idPaket
		{
			get
			{
				return this._idPaket;
			}
			set
			{
				if ((this._idPaket != value))
				{
					if (this._Paket.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPaketChanging(value);
					this.SendPropertyChanging();
					this._idPaket = value;
					this.SendPropertyChanged("idPaket");
					this.OnidPaketChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Harga", DbType="Int NOT NULL")]
		public int Harga
		{
			get
			{
				return this._Harga;
			}
			set
			{
				if ((this._Harga != value))
				{
					this.OnHargaChanging(value);
					this.SendPropertyChanging();
					this._Harga = value;
					this.SendPropertyChanged("Harga");
					this.OnHargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TanggalMulai", DbType="DateTime NOT NULL")]
		public System.DateTime TanggalMulai
		{
			get
			{
				return this._TanggalMulai;
			}
			set
			{
				if ((this._TanggalMulai != value))
				{
					this.OnTanggalMulaiChanging(value);
					this.SendPropertyChanging();
					this._TanggalMulai = value;
					this.SendPropertyChanged("TanggalMulai");
					this.OnTanggalMulaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TanggalSelesai", DbType="DateTime")]
		public System.Nullable<System.DateTime> TanggalSelesai
		{
			get
			{
				return this._TanggalSelesai;
			}
			set
			{
				if ((this._TanggalSelesai != value))
				{
					this.OnTanggalSelesaiChanging(value);
					this.SendPropertyChanging();
					this._TanggalSelesai = value;
					this.SendPropertyChanged("TanggalSelesai");
					this.OnTanggalSelesaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DetailPaket_DetailTransaksi", Storage="_DetailTransaksis", ThisKey="id", OtherKey="idDetailPaket")]
		public EntitySet<DetailTransaksi> DetailTransaksis
		{
			get
			{
				return this._DetailTransaksis;
			}
			set
			{
				this._DetailTransaksis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Paket_DetailPaket", Storage="_Paket", ThisKey="idPaket", OtherKey="id", IsForeignKey=true)]
		public Paket Paket
		{
			get
			{
				return this._Paket.Entity;
			}
			set
			{
				Paket previousValue = this._Paket.Entity;
				if (((previousValue != value) 
							|| (this._Paket.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Paket.Entity = null;
						previousValue.DetailPakets.Remove(this);
					}
					this._Paket.Entity = value;
					if ((value != null))
					{
						value.DetailPakets.Add(this);
						this._idPaket = value.id;
					}
					else
					{
						this._idPaket = default(int);
					}
					this.SendPropertyChanged("Paket");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pelanggan_DetailPaket", Storage="_Pelanggan", ThisKey="idPelanggan", OtherKey="id", IsForeignKey=true)]
		public Pelanggan Pelanggan
		{
			get
			{
				return this._Pelanggan.Entity;
			}
			set
			{
				Pelanggan previousValue = this._Pelanggan.Entity;
				if (((previousValue != value) 
							|| (this._Pelanggan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Pelanggan.Entity = null;
						previousValue.DetailPakets.Remove(this);
					}
					this._Pelanggan.Entity = value;
					if ((value != null))
					{
						value.DetailPakets.Add(this);
						this._idPelanggan = value.id;
					}
					else
					{
						this._idPelanggan = default(int);
					}
					this.SendPropertyChanged("Pelanggan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DetailTransaksis(DetailTransaksi entity)
		{
			this.SendPropertyChanging();
			entity.DetailPaket = this;
		}
		
		private void detach_DetailTransaksis(DetailTransaksi entity)
		{
			this.SendPropertyChanging();
			entity.DetailPaket = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DetailTransaksi")]
	public partial class DetailTransaksi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _idTransaksi;
		
		private int _idLayanan;
		
		private System.Nullable<int> _idDetailPaket;
		
		private int _HargaUnit;
		
		private double _TotalUnit;
		
		private System.Nullable<System.DateTime> _TanggalSelesai;
		
		private EntityRef<DetailPaket> _DetailPaket;
		
		private EntityRef<Layanan> _Layanan;
		
		private EntityRef<Transaksi> _Transaksi;
		
		private EntityRef<Transaksi1> _Transaksi1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidTransaksiChanging(int value);
    partial void OnidTransaksiChanged();
    partial void OnidLayananChanging(int value);
    partial void OnidLayananChanged();
    partial void OnidDetailPaketChanging(System.Nullable<int> value);
    partial void OnidDetailPaketChanged();
    partial void OnHargaUnitChanging(int value);
    partial void OnHargaUnitChanged();
    partial void OnTotalUnitChanging(double value);
    partial void OnTotalUnitChanged();
    partial void OnTanggalSelesaiChanging(System.Nullable<System.DateTime> value);
    partial void OnTanggalSelesaiChanged();
    #endregion
		
		public DetailTransaksi()
		{
			this._DetailPaket = default(EntityRef<DetailPaket>);
			this._Layanan = default(EntityRef<Layanan>);
			this._Transaksi = default(EntityRef<Transaksi>);
			this._Transaksi1 = default(EntityRef<Transaksi1>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTransaksi", DbType="Int NOT NULL")]
		public int idTransaksi
		{
			get
			{
				return this._idTransaksi;
			}
			set
			{
				if ((this._idTransaksi != value))
				{
					if ((this._Transaksi.HasLoadedOrAssignedValue || this._Transaksi1.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTransaksiChanging(value);
					this.SendPropertyChanging();
					this._idTransaksi = value;
					this.SendPropertyChanged("idTransaksi");
					this.OnidTransaksiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idLayanan", DbType="Int NOT NULL")]
		public int idLayanan
		{
			get
			{
				return this._idLayanan;
			}
			set
			{
				if ((this._idLayanan != value))
				{
					if (this._Layanan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidLayananChanging(value);
					this.SendPropertyChanging();
					this._idLayanan = value;
					this.SendPropertyChanged("idLayanan");
					this.OnidLayananChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDetailPaket", DbType="Int")]
		public System.Nullable<int> idDetailPaket
		{
			get
			{
				return this._idDetailPaket;
			}
			set
			{
				if ((this._idDetailPaket != value))
				{
					if (this._DetailPaket.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidDetailPaketChanging(value);
					this.SendPropertyChanging();
					this._idDetailPaket = value;
					this.SendPropertyChanged("idDetailPaket");
					this.OnidDetailPaketChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HargaUnit", DbType="Int NOT NULL")]
		public int HargaUnit
		{
			get
			{
				return this._HargaUnit;
			}
			set
			{
				if ((this._HargaUnit != value))
				{
					this.OnHargaUnitChanging(value);
					this.SendPropertyChanging();
					this._HargaUnit = value;
					this.SendPropertyChanged("HargaUnit");
					this.OnHargaUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalUnit", DbType="Float NOT NULL")]
		public double TotalUnit
		{
			get
			{
				return this._TotalUnit;
			}
			set
			{
				if ((this._TotalUnit != value))
				{
					this.OnTotalUnitChanging(value);
					this.SendPropertyChanging();
					this._TotalUnit = value;
					this.SendPropertyChanged("TotalUnit");
					this.OnTotalUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TanggalSelesai", DbType="DateTime")]
		public System.Nullable<System.DateTime> TanggalSelesai
		{
			get
			{
				return this._TanggalSelesai;
			}
			set
			{
				if ((this._TanggalSelesai != value))
				{
					this.OnTanggalSelesaiChanging(value);
					this.SendPropertyChanging();
					this._TanggalSelesai = value;
					this.SendPropertyChanged("TanggalSelesai");
					this.OnTanggalSelesaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DetailPaket_DetailTransaksi", Storage="_DetailPaket", ThisKey="idDetailPaket", OtherKey="id", IsForeignKey=true)]
		public DetailPaket DetailPaket
		{
			get
			{
				return this._DetailPaket.Entity;
			}
			set
			{
				DetailPaket previousValue = this._DetailPaket.Entity;
				if (((previousValue != value) 
							|| (this._DetailPaket.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DetailPaket.Entity = null;
						previousValue.DetailTransaksis.Remove(this);
					}
					this._DetailPaket.Entity = value;
					if ((value != null))
					{
						value.DetailTransaksis.Add(this);
						this._idDetailPaket = value.id;
					}
					else
					{
						this._idDetailPaket = default(Nullable<int>);
					}
					this.SendPropertyChanged("DetailPaket");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Layanan_DetailTransaksi", Storage="_Layanan", ThisKey="idLayanan", OtherKey="id", IsForeignKey=true)]
		public Layanan Layanan
		{
			get
			{
				return this._Layanan.Entity;
			}
			set
			{
				Layanan previousValue = this._Layanan.Entity;
				if (((previousValue != value) 
							|| (this._Layanan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Layanan.Entity = null;
						previousValue.DetailTransaksis.Remove(this);
					}
					this._Layanan.Entity = value;
					if ((value != null))
					{
						value.DetailTransaksis.Add(this);
						this._idLayanan = value.id;
					}
					else
					{
						this._idLayanan = default(int);
					}
					this.SendPropertyChanged("Layanan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Transaksi_DetailTransaksi", Storage="_Transaksi", ThisKey="idTransaksi", OtherKey="id", IsForeignKey=true)]
		public Transaksi Transaksi
		{
			get
			{
				return this._Transaksi.Entity;
			}
			set
			{
				Transaksi previousValue = this._Transaksi.Entity;
				if (((previousValue != value) 
							|| (this._Transaksi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Transaksi.Entity = null;
						previousValue.DetailTransaksis.Remove(this);
					}
					this._Transaksi.Entity = value;
					if ((value != null))
					{
						value.DetailTransaksis.Add(this);
						this._idTransaksi = value.id;
					}
					else
					{
						this._idTransaksi = default(int);
					}
					this.SendPropertyChanged("Transaksi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Transaksi1_DetailTransaksi", Storage="_Transaksi1", ThisKey="idTransaksi", OtherKey="id", IsForeignKey=true)]
		public Transaksi1 Transaksi1
		{
			get
			{
				return this._Transaksi1.Entity;
			}
			set
			{
				Transaksi1 previousValue = this._Transaksi1.Entity;
				if (((previousValue != value) 
							|| (this._Transaksi1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Transaksi1.Entity = null;
						previousValue.DetailTransaksis.Remove(this);
					}
					this._Transaksi1.Entity = value;
					if ((value != null))
					{
						value.DetailTransaksis.Add(this);
						this._idTransaksi = value.id;
					}
					else
					{
						this._idTransaksi = default(int);
					}
					this.SendPropertyChanged("Transaksi1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Jabatan")]
	public partial class Jabatan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _NamaJabatan;
		
		private EntitySet<Pegawai> _Pegawais;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnNamaJabatanChanging(string value);
    partial void OnNamaJabatanChanged();
    #endregion
		
		public Jabatan()
		{
			this._Pegawais = new EntitySet<Pegawai>(new Action<Pegawai>(this.attach_Pegawais), new Action<Pegawai>(this.detach_Pegawais));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamaJabatan", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NamaJabatan
		{
			get
			{
				return this._NamaJabatan;
			}
			set
			{
				if ((this._NamaJabatan != value))
				{
					this.OnNamaJabatanChanging(value);
					this.SendPropertyChanging();
					this._NamaJabatan = value;
					this.SendPropertyChanged("NamaJabatan");
					this.OnNamaJabatanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Jabatan_Pegawai", Storage="_Pegawais", ThisKey="id", OtherKey="idJabatan")]
		public EntitySet<Pegawai> Pegawais
		{
			get
			{
				return this._Pegawais;
			}
			set
			{
				this._Pegawais.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Pegawais(Pegawai entity)
		{
			this.SendPropertyChanging();
			entity.Jabatan = this;
		}
		
		private void detach_Pegawais(Pegawai entity)
		{
			this.SendPropertyChanging();
			entity.Jabatan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kategori")]
	public partial class Kategori : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Nama;
		
		private EntitySet<Layanan> _Layanans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnNamaChanging(string value);
    partial void OnNamaChanged();
    #endregion
		
		public Kategori()
		{
			this._Layanans = new EntitySet<Layanan>(new Action<Layanan>(this.attach_Layanans), new Action<Layanan>(this.detach_Layanans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nama", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nama
		{
			get
			{
				return this._Nama;
			}
			set
			{
				if ((this._Nama != value))
				{
					this.OnNamaChanging(value);
					this.SendPropertyChanging();
					this._Nama = value;
					this.SendPropertyChanged("Nama");
					this.OnNamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kategori_Layanan", Storage="_Layanans", ThisKey="id", OtherKey="idKategori")]
		public EntitySet<Layanan> Layanans
		{
			get
			{
				return this._Layanans;
			}
			set
			{
				this._Layanans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Layanans(Layanan entity)
		{
			this.SendPropertyChanging();
			entity.Kategori = this;
		}
		
		private void detach_Layanans(Layanan entity)
		{
			this.SendPropertyChanging();
			entity.Kategori = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Layanan")]
	public partial class Layanan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Nama;
		
		private int _idKategori;
		
		private int _idUnit;
		
		private int _HargaUnit;
		
		private int _EstimasiDurasi;
		
		private EntitySet<DetailTransaksi> _DetailTransaksis;
		
		private EntityRef<Kategori> _Kategori;
		
		private EntityRef<Unit> _Unit;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnNamaChanging(string value);
    partial void OnNamaChanged();
    partial void OnidKategoriChanging(int value);
    partial void OnidKategoriChanged();
    partial void OnidUnitChanging(int value);
    partial void OnidUnitChanged();
    partial void OnHargaUnitChanging(int value);
    partial void OnHargaUnitChanged();
    partial void OnEstimasiDurasiChanging(int value);
    partial void OnEstimasiDurasiChanged();
    #endregion
		
		public Layanan()
		{
			this._DetailTransaksis = new EntitySet<DetailTransaksi>(new Action<DetailTransaksi>(this.attach_DetailTransaksis), new Action<DetailTransaksi>(this.detach_DetailTransaksis));
			this._Kategori = default(EntityRef<Kategori>);
			this._Unit = default(EntityRef<Unit>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nama", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nama
		{
			get
			{
				return this._Nama;
			}
			set
			{
				if ((this._Nama != value))
				{
					this.OnNamaChanging(value);
					this.SendPropertyChanging();
					this._Nama = value;
					this.SendPropertyChanged("Nama");
					this.OnNamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idKategori", DbType="Int NOT NULL")]
		public int idKategori
		{
			get
			{
				return this._idKategori;
			}
			set
			{
				if ((this._idKategori != value))
				{
					if (this._Kategori.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidKategoriChanging(value);
					this.SendPropertyChanging();
					this._idKategori = value;
					this.SendPropertyChanged("idKategori");
					this.OnidKategoriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUnit", DbType="Int NOT NULL")]
		public int idUnit
		{
			get
			{
				return this._idUnit;
			}
			set
			{
				if ((this._idUnit != value))
				{
					if (this._Unit.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidUnitChanging(value);
					this.SendPropertyChanging();
					this._idUnit = value;
					this.SendPropertyChanged("idUnit");
					this.OnidUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HargaUnit", DbType="Int NOT NULL")]
		public int HargaUnit
		{
			get
			{
				return this._HargaUnit;
			}
			set
			{
				if ((this._HargaUnit != value))
				{
					this.OnHargaUnitChanging(value);
					this.SendPropertyChanging();
					this._HargaUnit = value;
					this.SendPropertyChanged("HargaUnit");
					this.OnHargaUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstimasiDurasi", DbType="Int NOT NULL")]
		public int EstimasiDurasi
		{
			get
			{
				return this._EstimasiDurasi;
			}
			set
			{
				if ((this._EstimasiDurasi != value))
				{
					this.OnEstimasiDurasiChanging(value);
					this.SendPropertyChanging();
					this._EstimasiDurasi = value;
					this.SendPropertyChanged("EstimasiDurasi");
					this.OnEstimasiDurasiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Layanan_DetailTransaksi", Storage="_DetailTransaksis", ThisKey="id", OtherKey="idLayanan")]
		public EntitySet<DetailTransaksi> DetailTransaksis
		{
			get
			{
				return this._DetailTransaksis;
			}
			set
			{
				this._DetailTransaksis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kategori_Layanan", Storage="_Kategori", ThisKey="idKategori", OtherKey="id", IsForeignKey=true)]
		public Kategori Kategori
		{
			get
			{
				return this._Kategori.Entity;
			}
			set
			{
				Kategori previousValue = this._Kategori.Entity;
				if (((previousValue != value) 
							|| (this._Kategori.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kategori.Entity = null;
						previousValue.Layanans.Remove(this);
					}
					this._Kategori.Entity = value;
					if ((value != null))
					{
						value.Layanans.Add(this);
						this._idKategori = value.id;
					}
					else
					{
						this._idKategori = default(int);
					}
					this.SendPropertyChanged("Kategori");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Unit_Layanan", Storage="_Unit", ThisKey="idUnit", OtherKey="id", IsForeignKey=true)]
		public Unit Unit
		{
			get
			{
				return this._Unit.Entity;
			}
			set
			{
				Unit previousValue = this._Unit.Entity;
				if (((previousValue != value) 
							|| (this._Unit.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Unit.Entity = null;
						previousValue.Layanans.Remove(this);
					}
					this._Unit.Entity = value;
					if ((value != null))
					{
						value.Layanans.Add(this);
						this._idUnit = value.id;
					}
					else
					{
						this._idUnit = default(int);
					}
					this.SendPropertyChanged("Unit");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DetailTransaksis(DetailTransaksi entity)
		{
			this.SendPropertyChanging();
			entity.Layanan = this;
		}
		
		private void detach_DetailTransaksis(DetailTransaksi entity)
		{
			this.SendPropertyChanging();
			entity.Layanan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Paket")]
	public partial class Paket : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _idLayanan;
		
		private int _TotalUnit;
		
		private int _Harga;
		
		private string _Nama;
		
		private EntitySet<DetailPaket> _DetailPakets;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidLayananChanging(int value);
    partial void OnidLayananChanged();
    partial void OnTotalUnitChanging(int value);
    partial void OnTotalUnitChanged();
    partial void OnHargaChanging(int value);
    partial void OnHargaChanged();
    partial void OnNamaChanging(string value);
    partial void OnNamaChanged();
    #endregion
		
		public Paket()
		{
			this._DetailPakets = new EntitySet<DetailPaket>(new Action<DetailPaket>(this.attach_DetailPakets), new Action<DetailPaket>(this.detach_DetailPakets));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idLayanan", DbType="Int NOT NULL")]
		public int idLayanan
		{
			get
			{
				return this._idLayanan;
			}
			set
			{
				if ((this._idLayanan != value))
				{
					this.OnidLayananChanging(value);
					this.SendPropertyChanging();
					this._idLayanan = value;
					this.SendPropertyChanged("idLayanan");
					this.OnidLayananChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalUnit", DbType="Int NOT NULL")]
		public int TotalUnit
		{
			get
			{
				return this._TotalUnit;
			}
			set
			{
				if ((this._TotalUnit != value))
				{
					this.OnTotalUnitChanging(value);
					this.SendPropertyChanging();
					this._TotalUnit = value;
					this.SendPropertyChanged("TotalUnit");
					this.OnTotalUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Harga", DbType="Int NOT NULL")]
		public int Harga
		{
			get
			{
				return this._Harga;
			}
			set
			{
				if ((this._Harga != value))
				{
					this.OnHargaChanging(value);
					this.SendPropertyChanging();
					this._Harga = value;
					this.SendPropertyChanged("Harga");
					this.OnHargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nama", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nama
		{
			get
			{
				return this._Nama;
			}
			set
			{
				if ((this._Nama != value))
				{
					this.OnNamaChanging(value);
					this.SendPropertyChanging();
					this._Nama = value;
					this.SendPropertyChanged("Nama");
					this.OnNamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Paket_DetailPaket", Storage="_DetailPakets", ThisKey="id", OtherKey="idPaket")]
		public EntitySet<DetailPaket> DetailPakets
		{
			get
			{
				return this._DetailPakets;
			}
			set
			{
				this._DetailPakets.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DetailPakets(DetailPaket entity)
		{
			this.SendPropertyChanging();
			entity.Paket = this;
		}
		
		private void detach_DetailPakets(DetailPaket entity)
		{
			this.SendPropertyChanging();
			entity.Paket = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pegawai")]
	public partial class Pegawai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Password;
		
		private string _Nama;
		
		private string _Email;
		
		private string _Alamat;
		
		private string _Notelp;
		
		private System.Nullable<System.DateTime> _TglLahir;
		
		private int _idJabatan;
		
		private EntityRef<Jabatan> _Jabatan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnNamaChanging(string value);
    partial void OnNamaChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnAlamatChanging(string value);
    partial void OnAlamatChanged();
    partial void OnNotelpChanging(string value);
    partial void OnNotelpChanged();
    partial void OnTglLahirChanging(System.Nullable<System.DateTime> value);
    partial void OnTglLahirChanged();
    partial void OnidJabatanChanging(int value);
    partial void OnidJabatanChanged();
    #endregion
		
		public Pegawai()
		{
			this._Jabatan = default(EntityRef<Jabatan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nama", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nama
		{
			get
			{
				return this._Nama;
			}
			set
			{
				if ((this._Nama != value))
				{
					this.OnNamaChanging(value);
					this.SendPropertyChanging();
					this._Nama = value;
					this.SendPropertyChanged("Nama");
					this.OnNamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alamat", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Alamat
		{
			get
			{
				return this._Alamat;
			}
			set
			{
				if ((this._Alamat != value))
				{
					this.OnAlamatChanging(value);
					this.SendPropertyChanging();
					this._Alamat = value;
					this.SendPropertyChanged("Alamat");
					this.OnAlamatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notelp", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Notelp
		{
			get
			{
				return this._Notelp;
			}
			set
			{
				if ((this._Notelp != value))
				{
					this.OnNotelpChanging(value);
					this.SendPropertyChanging();
					this._Notelp = value;
					this.SendPropertyChanged("Notelp");
					this.OnNotelpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TglLahir", DbType="Date")]
		public System.Nullable<System.DateTime> TglLahir
		{
			get
			{
				return this._TglLahir;
			}
			set
			{
				if ((this._TglLahir != value))
				{
					this.OnTglLahirChanging(value);
					this.SendPropertyChanging();
					this._TglLahir = value;
					this.SendPropertyChanged("TglLahir");
					this.OnTglLahirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idJabatan", DbType="Int NOT NULL")]
		public int idJabatan
		{
			get
			{
				return this._idJabatan;
			}
			set
			{
				if ((this._idJabatan != value))
				{
					if (this._Jabatan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidJabatanChanging(value);
					this.SendPropertyChanging();
					this._idJabatan = value;
					this.SendPropertyChanged("idJabatan");
					this.OnidJabatanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Jabatan_Pegawai", Storage="_Jabatan", ThisKey="idJabatan", OtherKey="id", IsForeignKey=true)]
		public Jabatan Jabatan
		{
			get
			{
				return this._Jabatan.Entity;
			}
			set
			{
				Jabatan previousValue = this._Jabatan.Entity;
				if (((previousValue != value) 
							|| (this._Jabatan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Jabatan.Entity = null;
						previousValue.Pegawais.Remove(this);
					}
					this._Jabatan.Entity = value;
					if ((value != null))
					{
						value.Pegawais.Add(this);
						this._idJabatan = value.id;
					}
					else
					{
						this._idJabatan = default(int);
					}
					this.SendPropertyChanged("Jabatan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pelanggan")]
	public partial class Pelanggan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Nama;
		
		private string _Notelp;
		
		private string _Alamat;
		
		private EntitySet<DetailPaket> _DetailPakets;
		
		private EntitySet<Voucher> _Vouchers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnNamaChanging(string value);
    partial void OnNamaChanged();
    partial void OnNotelpChanging(string value);
    partial void OnNotelpChanged();
    partial void OnAlamatChanging(string value);
    partial void OnAlamatChanged();
    #endregion
		
		public Pelanggan()
		{
			this._DetailPakets = new EntitySet<DetailPaket>(new Action<DetailPaket>(this.attach_DetailPakets), new Action<DetailPaket>(this.detach_DetailPakets));
			this._Vouchers = new EntitySet<Voucher>(new Action<Voucher>(this.attach_Vouchers), new Action<Voucher>(this.detach_Vouchers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nama", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nama
		{
			get
			{
				return this._Nama;
			}
			set
			{
				if ((this._Nama != value))
				{
					this.OnNamaChanging(value);
					this.SendPropertyChanging();
					this._Nama = value;
					this.SendPropertyChanged("Nama");
					this.OnNamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notelp", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Notelp
		{
			get
			{
				return this._Notelp;
			}
			set
			{
				if ((this._Notelp != value))
				{
					this.OnNotelpChanging(value);
					this.SendPropertyChanging();
					this._Notelp = value;
					this.SendPropertyChanged("Notelp");
					this.OnNotelpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alamat", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Alamat
		{
			get
			{
				return this._Alamat;
			}
			set
			{
				if ((this._Alamat != value))
				{
					this.OnAlamatChanging(value);
					this.SendPropertyChanging();
					this._Alamat = value;
					this.SendPropertyChanged("Alamat");
					this.OnAlamatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pelanggan_DetailPaket", Storage="_DetailPakets", ThisKey="id", OtherKey="idPelanggan")]
		public EntitySet<DetailPaket> DetailPakets
		{
			get
			{
				return this._DetailPakets;
			}
			set
			{
				this._DetailPakets.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pelanggan_Voucher", Storage="_Vouchers", ThisKey="id", OtherKey="idPelanggan")]
		public EntitySet<Voucher> Vouchers
		{
			get
			{
				return this._Vouchers;
			}
			set
			{
				this._Vouchers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DetailPakets(DetailPaket entity)
		{
			this.SendPropertyChanging();
			entity.Pelanggan = this;
		}
		
		private void detach_DetailPakets(DetailPaket entity)
		{
			this.SendPropertyChanging();
			entity.Pelanggan = null;
		}
		
		private void attach_Vouchers(Voucher entity)
		{
			this.SendPropertyChanging();
			entity.Pelanggan = this;
		}
		
		private void detach_Vouchers(Voucher entity)
		{
			this.SendPropertyChanging();
			entity.Pelanggan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Transaksi")]
	public partial class Transaksi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _idPelanggan;
		
		private int _IdPegawai;
		
		private System.Nullable<System.DateTime> _TanggalTransaksi;
		
		private System.Nullable<System.DateTime> _EstimasiSelesai;
		
		private EntitySet<DetailTransaksi> _DetailTransaksis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidPelangganChanging(int value);
    partial void OnidPelangganChanged();
    partial void OnIdPegawaiChanging(int value);
    partial void OnIdPegawaiChanged();
    partial void OnTanggalTransaksiChanging(System.Nullable<System.DateTime> value);
    partial void OnTanggalTransaksiChanged();
    partial void OnEstimasiSelesaiChanging(System.Nullable<System.DateTime> value);
    partial void OnEstimasiSelesaiChanged();
    #endregion
		
		public Transaksi()
		{
			this._DetailTransaksis = new EntitySet<DetailTransaksi>(new Action<DetailTransaksi>(this.attach_DetailTransaksis), new Action<DetailTransaksi>(this.detach_DetailTransaksis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPelanggan", DbType="Int NOT NULL")]
		public int idPelanggan
		{
			get
			{
				return this._idPelanggan;
			}
			set
			{
				if ((this._idPelanggan != value))
				{
					this.OnidPelangganChanging(value);
					this.SendPropertyChanging();
					this._idPelanggan = value;
					this.SendPropertyChanged("idPelanggan");
					this.OnidPelangganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPegawai", DbType="Int NOT NULL")]
		public int IdPegawai
		{
			get
			{
				return this._IdPegawai;
			}
			set
			{
				if ((this._IdPegawai != value))
				{
					this.OnIdPegawaiChanging(value);
					this.SendPropertyChanging();
					this._IdPegawai = value;
					this.SendPropertyChanged("IdPegawai");
					this.OnIdPegawaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TanggalTransaksi", DbType="DateTime")]
		public System.Nullable<System.DateTime> TanggalTransaksi
		{
			get
			{
				return this._TanggalTransaksi;
			}
			set
			{
				if ((this._TanggalTransaksi != value))
				{
					this.OnTanggalTransaksiChanging(value);
					this.SendPropertyChanging();
					this._TanggalTransaksi = value;
					this.SendPropertyChanged("TanggalTransaksi");
					this.OnTanggalTransaksiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstimasiSelesai", DbType="DateTime")]
		public System.Nullable<System.DateTime> EstimasiSelesai
		{
			get
			{
				return this._EstimasiSelesai;
			}
			set
			{
				if ((this._EstimasiSelesai != value))
				{
					this.OnEstimasiSelesaiChanging(value);
					this.SendPropertyChanging();
					this._EstimasiSelesai = value;
					this.SendPropertyChanged("EstimasiSelesai");
					this.OnEstimasiSelesaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Transaksi_DetailTransaksi", Storage="_DetailTransaksis", ThisKey="id", OtherKey="idTransaksi")]
		public EntitySet<DetailTransaksi> DetailTransaksis
		{
			get
			{
				return this._DetailTransaksis;
			}
			set
			{
				this._DetailTransaksis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DetailTransaksis(DetailTransaksi entity)
		{
			this.SendPropertyChanging();
			entity.Transaksi = this;
		}
		
		private void detach_DetailTransaksis(DetailTransaksi entity)
		{
			this.SendPropertyChanging();
			entity.Transaksi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Unit")]
	public partial class Unit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Nama;
		
		private EntitySet<Layanan> _Layanans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnNamaChanging(string value);
    partial void OnNamaChanged();
    #endregion
		
		public Unit()
		{
			this._Layanans = new EntitySet<Layanan>(new Action<Layanan>(this.attach_Layanans), new Action<Layanan>(this.detach_Layanans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nama", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nama
		{
			get
			{
				return this._Nama;
			}
			set
			{
				if ((this._Nama != value))
				{
					this.OnNamaChanging(value);
					this.SendPropertyChanging();
					this._Nama = value;
					this.SendPropertyChanged("Nama");
					this.OnNamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Unit_Layanan", Storage="_Layanans", ThisKey="id", OtherKey="idUnit")]
		public EntitySet<Layanan> Layanans
		{
			get
			{
				return this._Layanans;
			}
			set
			{
				this._Layanans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Layanans(Layanan entity)
		{
			this.SendPropertyChanging();
			entity.Unit = this;
		}
		
		private void detach_Layanans(Layanan entity)
		{
			this.SendPropertyChanging();
			entity.Unit = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Voucher")]
	public partial class Voucher : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Kode;
		
		private System.Nullable<int> _PotonganHarga;
		
		private int _idPelanggan;
		
		private EntityRef<Pelanggan> _Pelanggan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnKodeChanging(string value);
    partial void OnKodeChanged();
    partial void OnPotonganHargaChanging(System.Nullable<int> value);
    partial void OnPotonganHargaChanged();
    partial void OnidPelangganChanging(int value);
    partial void OnidPelangganChanged();
    #endregion
		
		public Voucher()
		{
			this._Pelanggan = default(EntityRef<Pelanggan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kode", DbType="VarChar(50)")]
		public string Kode
		{
			get
			{
				return this._Kode;
			}
			set
			{
				if ((this._Kode != value))
				{
					this.OnKodeChanging(value);
					this.SendPropertyChanging();
					this._Kode = value;
					this.SendPropertyChanged("Kode");
					this.OnKodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PotonganHarga", DbType="Int")]
		public System.Nullable<int> PotonganHarga
		{
			get
			{
				return this._PotonganHarga;
			}
			set
			{
				if ((this._PotonganHarga != value))
				{
					this.OnPotonganHargaChanging(value);
					this.SendPropertyChanging();
					this._PotonganHarga = value;
					this.SendPropertyChanged("PotonganHarga");
					this.OnPotonganHargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPelanggan", DbType="Int NOT NULL")]
		public int idPelanggan
		{
			get
			{
				return this._idPelanggan;
			}
			set
			{
				if ((this._idPelanggan != value))
				{
					if (this._Pelanggan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPelangganChanging(value);
					this.SendPropertyChanging();
					this._idPelanggan = value;
					this.SendPropertyChanged("idPelanggan");
					this.OnidPelangganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pelanggan_Voucher", Storage="_Pelanggan", ThisKey="idPelanggan", OtherKey="id", IsForeignKey=true)]
		public Pelanggan Pelanggan
		{
			get
			{
				return this._Pelanggan.Entity;
			}
			set
			{
				Pelanggan previousValue = this._Pelanggan.Entity;
				if (((previousValue != value) 
							|| (this._Pelanggan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Pelanggan.Entity = null;
						previousValue.Vouchers.Remove(this);
					}
					this._Pelanggan.Entity = value;
					if ((value != null))
					{
						value.Vouchers.Add(this);
						this._idPelanggan = value.id;
					}
					else
					{
						this._idPelanggan = default(int);
					}
					this.SendPropertyChanged("Pelanggan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Transaksi")]
	public partial class Transaksi1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _idPelanggan;
		
		private int _IdPegawai;
		
		private System.Nullable<System.DateTime> _TanggalTransaksi;
		
		private System.Nullable<System.DateTime> _EstimasiSelesai;
		
		private EntitySet<DetailTransaksi> _DetailTransaksis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidPelangganChanging(int value);
    partial void OnidPelangganChanged();
    partial void OnIdPegawaiChanging(int value);
    partial void OnIdPegawaiChanged();
    partial void OnTanggalTransaksiChanging(System.Nullable<System.DateTime> value);
    partial void OnTanggalTransaksiChanged();
    partial void OnEstimasiSelesaiChanging(System.Nullable<System.DateTime> value);
    partial void OnEstimasiSelesaiChanged();
    #endregion
		
		public Transaksi1()
		{
			this._DetailTransaksis = new EntitySet<DetailTransaksi>(new Action<DetailTransaksi>(this.attach_DetailTransaksis), new Action<DetailTransaksi>(this.detach_DetailTransaksis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPelanggan", DbType="Int NOT NULL")]
		public int idPelanggan
		{
			get
			{
				return this._idPelanggan;
			}
			set
			{
				if ((this._idPelanggan != value))
				{
					this.OnidPelangganChanging(value);
					this.SendPropertyChanging();
					this._idPelanggan = value;
					this.SendPropertyChanged("idPelanggan");
					this.OnidPelangganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPegawai", DbType="Int NOT NULL")]
		public int IdPegawai
		{
			get
			{
				return this._IdPegawai;
			}
			set
			{
				if ((this._IdPegawai != value))
				{
					this.OnIdPegawaiChanging(value);
					this.SendPropertyChanging();
					this._IdPegawai = value;
					this.SendPropertyChanged("IdPegawai");
					this.OnIdPegawaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TanggalTransaksi", DbType="DateTime")]
		public System.Nullable<System.DateTime> TanggalTransaksi
		{
			get
			{
				return this._TanggalTransaksi;
			}
			set
			{
				if ((this._TanggalTransaksi != value))
				{
					this.OnTanggalTransaksiChanging(value);
					this.SendPropertyChanging();
					this._TanggalTransaksi = value;
					this.SendPropertyChanged("TanggalTransaksi");
					this.OnTanggalTransaksiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstimasiSelesai", DbType="DateTime")]
		public System.Nullable<System.DateTime> EstimasiSelesai
		{
			get
			{
				return this._EstimasiSelesai;
			}
			set
			{
				if ((this._EstimasiSelesai != value))
				{
					this.OnEstimasiSelesaiChanging(value);
					this.SendPropertyChanging();
					this._EstimasiSelesai = value;
					this.SendPropertyChanged("EstimasiSelesai");
					this.OnEstimasiSelesaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Transaksi1_DetailTransaksi", Storage="_DetailTransaksis", ThisKey="id", OtherKey="idTransaksi")]
		public EntitySet<DetailTransaksi> DetailTransaksis
		{
			get
			{
				return this._DetailTransaksis;
			}
			set
			{
				this._DetailTransaksis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DetailTransaksis(DetailTransaksi entity)
		{
			this.SendPropertyChanging();
			entity.Transaksi1 = this;
		}
		
		private void detach_DetailTransaksis(DetailTransaksi entity)
		{
			this.SendPropertyChanging();
			entity.Transaksi1 = null;
		}
	}
}
#pragma warning restore 1591
